platform :ios, '8.0'
inhibit_all_warnings!
target 'AirSandboxDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'AirSandbox', :path => '../'

end
