platform :ios, '8.0'
inhibit_all_warnings!
target 'SKAirSandboxDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'SKAirSandbox', :path => '../'

end
